spring.application.name=InstaPound

spring.jpa.defer-datasource-initialization=true

storage.type=LOCAL
storage.local-path=./uploads
storage.thumbnail-path=./uploads/thumbnails

oktaDomain=https://integrator-8090155.okta.com/oauth2/default
oktaClientId=0oatstlwic0uQKcOi697
oktaClientSecret=787Q6Bjr3al4GhHbBvEQ_TJlTPk21tRPKXNzenDULKaCxkWzt_pZRcdmX6_Of5_R
redirectUri=http://localhost:8080/authorization-code/callback
scope=role username openid
grantType=authorization_code

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=55MB

logging.level.hr.algebra.nrako.instapound=INFO

spring.main.allow-bean-definition-overriding=true