spring.application.name=InstaPound

spring.jpa.defer-datasource-initialization=true

storage.type=BOTH
#storage.type=LOCAL
storage.local-path=./uploads
storage.thumbnail-path=./uploads/thumbnails

#storage.type=CLOUDINARY
storage.cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
storage.cloudinary.api-key=${CLOUDINARY_API_KEY}
storage.cloudinary.api-secret=${CLOUDINARY_API_SECRET}
storage.cloudinary.folder=instapound


spring.security.oauth2.client.registration.okta.client-id=${OKTA_CLIENT_ID}
spring.security.oauth2.client.registration.okta.client-secret=${OKTA_CLIENT_SECRET}
spring.security.oauth2.client.registration.okta.scope=openid,profile,email
spring.security.oauth2.client.registration.okta.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
#spring.security.oauth2.client.registration.okta.redirect-uri=http://localhost:5173/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.okta.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.okta.issuer-uri=${OKTA_ISSUER_URI}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=55MB

logging.level.hr.algebra.nrako.instapound=INFO

spring.main.allow-bean-definition-overriding=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
